import os
import copy

BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

sources = ['input_thread.c', 'input_dispatcher.c']

env=DefaultEnvironment().Clone()
env.Library(os.path.join(LIB_DIR, 'awtk_linux_fb'), sources)

env['LIBS'] = ['awtk_linux_fb'] + env['LIBS']
env.Program(os.path.join(BIN_DIR, 'input_test'), ["input_thread_test.c"])
